"use strict";
exports.__esModule = true;
var VARIABLE_DATA;
(function (VARIABLE_DATA) {
    VARIABLE_DATA["FETCH_REQUEST"] = "FETCH_REQUEST";
    VARIABLE_DATA["FETCH_SUCCESS"] = "FETCH_SUCCESS";
    VARIABLE_DATA["FETCH_FAILURE"] = "FETCH_FAILURE";
})(VARIABLE_DATA = exports.VARIABLE_DATA || (exports.VARIABLE_DATA = {}));
var VARIABLES;
(function (VARIABLES) {
    VARIABLES["FETCH_VARIABLE_NAMES_REQUEST"] = "FETCH_VARIABLE_NAMES_REQUEST";
    VARIABLES["FETCH_VARIABLE_NAMES_SUCCESS"] = "FETCH_VARIABLE_NAMES_SUCCESS";
    VARIABLES["FETCH_VARIABLE_NAMES_FAILURE"] = "FETCH_VARIABLE_NAMES_FAILURE";
    VARIABLES["SELECT_ACTIVE_VARIABLE"] = "SELECT_ACTIVE_VARIABLE";
})(VARIABLES = exports.VARIABLES || (exports.VARIABLES = {}));
